services:
  spark-master:
    image: fayadchowdhury/spark-4.0.0:v1
    # Uncomment the following lines to build the image from a Dockerfile
    # Comment out the 'image' line
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: spark-master
    command:
      - bash
      - -c
      - "/opt/spark/sbin/start-master.sh && tail -f /dev/null" # Keep the container running
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker-1:
    # Uncomment the following lines to build the image from a Dockerfile
    # Comment out the 'image' line
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: fayadchowdhury/spark-4.0.0:v1
    container_name: spark-worker-1
    command:
      - bash
      - -c
      - "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    # Uncomment the following lines to build the image from a Dockerfile
    # Comment out the 'image' line
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: fayadchowdhury/spark-4.0.0:v1
    container_name: spark-worker-2
    command:
      - bash
      - -c
      - "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
